[package]
name = "intmax-rollup-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
intmax-zkp-core = { git = "https://github.com/InternetMaximalism/intmax-zkp-core", rev = "a9bafd4447805849ddcb66596a4502578a3770f4" }
plonky2 = { git = "https://github.com/mir-protocol/plonky2", rev = "d527073416dd8cbc04457b8cb856b2fec3fa0e6c" }
serde = { version = "1.0", features = ["derive"] }
serde-hex = "0.1"
serde_json = "1.0"

[lib]
